# Generated by Django 5.1.8 on 2025-06-10 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codedocumentation',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdf_docs/'),
        ),
        migrations.AddField(
            model_name='codedocumentation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
